FROM ubuntu:24.04

# Install Java and tools
RUN apt-get update && apt-get install -y openjdk-8-jdk ssh rsync wget nano vim

# Set JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

RUN apt-get update && apt-get install -y openjdk-8-jdk wget
COPY hbase-2.5.11-bin.tar.gz /hbase-2.5.11-bin.tar.gz
RUN tar -xvzf hbase-2.5.11-bin.tar.gz -C /opt \
    && ln -sf /opt/hbase-2.5.11 /opt/hbase
ENV HBASE_HOME=/opt/hbase
ENV PATH=$PATH:$HBASE_HOME/bin
